alfresco:
  base-url: http://cms.cchtaxonline.com
  username: admin
  password: adm!n@cch123
  root-folder-id: -root-

client-export:
  base-download-url: https://your-api-host/api/v1/website-content/files

spring:
  application:
    name: contentexport