alfresco:
  base-url: http://cms.cchtaxonline.com
  username: username
  password: password
  root-folder-id: -root-

client-export:
  base-download-url: https://your-api-host/api/v1/website-content/files

spring:
  application:
    name: contentexport